---
title: "Exploring_structures"
author: "PW"
date: "2024-08-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(tibble)
library(dplyr)
library(ggplot2)
library(phsstyles)

```

# QPI and hospital data in a vector and a list


```{r hospitals}

# Vector of qpi names
qpi_vector <- c("Mindfulness support available", "Music therapy available", "Books", "TV")
qpi_vector[c(2,4)]
qpi_vector[3] <- "Reading material"
qpi_vector
# bad ways to print output
print(c("Here we have ", length(qpi_vector), " things.\n"))
print(paste0(qpi_vector[1:length(qpi_vector)]))
print(cat(qpi_vector))
# good ways to print output
str_c(qpi_vector[1], qpi_vector[4], "ooft", sep = "... a wee gap...")
# with newlines
cat(str_c(qpi_vector[1], qpi_vector[4], "ooft", sep = "... a wee gap... and newline \n"))

for (x in qpi_vector){
  print(x)
}


# Make a struc to keep details on hospitals
# name, code, avg beds, number of bus stops, cycle parking, number of cafes, non-smoking, 
# staff, depts, lat, long

# list representing one hospital
hosp_list <- list()
xlent_hosp <- list("Excellent hospital", "X808X", 2340.7665, 7, 17, 4, TRUE)
xlent_hosp[5]
xlent_hosp[c(1,3:5)]
xlent_hosp[1] <- "Most Excellent Hospital"
xlent_hosp
# remove the cafes 
xlent_hosp[-6]
xlent_hosp
# Is the code present? 
"X808H" %in% xlent_hosp
"X808X" %in% xlent_hosp
for(x in xlent_hosp){
  print(x)
}

```
# QPI and hospital data in data.table perhaps

```{r qpi_tabular_strux}

# Make a simple data frame
simple_qpi_df <- data.frame("QPI no." = c("1(i)", "1(ii)", "1(iii)", "3", "4(i)", "4(ii)", "5"),
                            Numerator_value = c(55, 8, 34, 101, 2, 10, 16),
                            Location = c("Leith Royal Infirmary", "Dr Helen's", "Golden Jubilee", "SRI", "Leith Royal Infirmary", "SRI", "SRI"))
names(simple_qpi_df)
str(simple_qpi_df)
ncol(simple_qpi_df)
nrow(simple_qpi_df)

simple_qpi_df$QPI.no.
simple_qpi_df[3]
simple_qpi_df 

# Store qpi performance in tibble
# with deliberate bad values
performance_tbl <- tibble(        "QPI no." = c("6", "7", "8(ii)", "8(iii)", "9", "10", "", "12", "12"),
                            numerator_value = c(151, 152, 153, 154, 155, 156, 157, 158, 159),
                          denominator_value = c(170, 178, 178, 178, 177, 161, 164, 0, 170),
                             numerator_text = c("Like strawberry ice cream", "Wear blue slippers?","Wear stripey pyjamas",
                                                "Read the paper", "Do sudoku", "Play chess", 
                                                "Get out for a walk each day", "Tai chi", "Judo") 
                             )
                      
names(performance_tbl)
str(performance_tbl)
class(performance_tbl)
performance_tbl$numerator_text[5]
performance_percent <- performance_tbl |>
  mutate(perform_pc = numerator_value / denominator_value)
```

# Health board or performance data in a matrix, not an array

```{r health_boards}

# Make a struc to keep details on HBs
# bounds maybe, name, code, avg beds, number of cafes, number of bus stops, cycle parking, staff, depts

# factor



# matrix 
# Must be two-dimensional, and all the same data type. 
# Uses less mem than data frame, but cannot be passed into ggplot. 
# In 99% of cases, tibble/df will be more convenient. 
# But some forms of linear algebra need a matrix. 
performance_2018_matrix <- matrix(c(99.1, 89.3, 77, 92.5, 95.6, 
                             98.012345, 88.80, 75.2, 90.09, 95.4
                             ),
                           nrow = 2,
                           ncol = 5
                           )

for (rows in 1:nrow(performance_2018_matrix)) {
  for (columns in 1:ncol(performance_2018_matrix)) {
    print(performance_2018_matrix[rows, columns])
  }
}

# array
# Like a matrix, ie all elements of the same type, 
# but can have numerous dimensions
# Might try to find a use-case. No rush. 

```

## Including Plots

You can also embed plots, for example:

```{r check_data}
# Look for missing values
plot_bar_chart <- performance_percent |>
  ggplot(aes(x = `QPI no.`, y = perform_pc)) +
  geom_col() +
  theme_phs()
plot_bar_chart

# Look for outliers
plot_for_outliers <- performance_percent |>
  ggplot(aes(x=denominator_value, y=numerator_value)) +
  geom_point(shape = 17) +
  theme_phs()
plot_for_outliers


```

