---
title: "Exploring data"
author: "PW"
date: "2024-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
```

## Changed Targets

Identify targets that have changed since the beginning of data gathering. 



```{r qpi_years} 
# Get background data 
tbl_background_data_age_gender <- read_excel("/conf/quality_indicators/Benchmarking/Cancer QPIs/Data/new_process/testing/test_bladder_24/excels_for_tableau/initial_run/input/Background_Data_Age_Gender.xlsx", 
    sheet = "Background_Data_Age_Gender")

summary(tbl_background_data_age_gender)

# Get case ascertainment data 
tbl_background_data_case <- read_excel("/conf/quality_indicators/Benchmarking/Cancer QPIs/Data/new_process/testing/test_bladder_24/excels_for_tableau/initial_run/input/Background_Data_Case.xlsx", 
    sheet = "Background_Data_Case")

summary(tbl_background_data_case)
# Get hb_hosp file from:  
# \Benchmarking\Cancer QPIs\Data\new_process\testing\test_bladder_24\excels_for_tableau\initial_run\input 

# tbl_hb_hosp_qpi <- 




```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
